### ISSUE TITLE
MetadataEntities and MetadataProperties scripts for seeding?

### ISSUE THREAD

**Issue by binhquan** [CTUIR/cdms-docs#1]
Ken - in the documentation for "Getting Started" | "Generate database option" step 6 (seed data),  you mention for metadata tables to contact you to provide the scripts.  Is there a way you can upload these scripts?

Thanks
binh

**Comment by kenburcham** [comment]
Hi Binh,
I was out of the country for several years and am back on this project. We will be posting a sample database that will include metadata sometime in the near future.  do you actually use the CDMS? :)
